### ISSUE TITLE
MCU pin assignment

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#20]
![image](https://user-images.githubusercontent.com/1595938/198113465-922fe878-8904-458f-a748-b95f4e2b759a.png)

I could not find working pin usage for the MCU.

Can you explain how the timer channels are used?

Most important part is that PWM outputs can't be properly used on timers that have encoder mode enabled, as in encoder mode the counter value is changed based on encoder inputs.

**Comment by dakoko** [comment]
I was unaware of the encoder mode and PWM output conflict. I changed the timers and pins around so that they'd be seperated from now on (new and old timer/pinout/channel setup is brought out in the pinout documentation spreadsheet file).

Timers 1, 3 and 4 are set to encoder mode. Timer 2 handles the thrower motor PWM, timer 8 the 3 motor PWMs and time 15 the servo PWMs.

For this fix I had to sacrifice the PWM input meant for the opto sensor and was replaced with an ADC. I will most likely handle the smoothing and other possible complications offboard.

**Comment by ReikoR** [comment]
For optical sensor it's probably best to use EXTI (external interrupt) as the sensor output is digital.
![image](https://user-images.githubusercontent.com/1595938/198883770-64834ea0-eb3d-480c-86a3-dc9eea59703d.png)

Otherwise new pin assignment might work.
